### ISSUE TITLE
Tracking issue for v0.2

### ISSUE THREAD

**Issue by GoldenBadger** [redbrick/good_stv#13]
- [x] Basic structure of web service
- [ ] API design
- [ ] Implementation of API endpoints
    - [ ] \[Add them here\]
